INSERT INTO T_USER (USERNAME, ACTIVE) VALUES('LadyJustice', 1);
INSERT INTO T_USER (USERNAME, ACTIVE) VALUES('Heisenberg', 1);
INSERT INTO T_USER (USERNAME, ACTIVE) VALUES('HardenJ', 0);

INSERT INTO T_CONTACT (EMAIL_ADDRESS, USER_ID) VALUES('master@email.com', 1);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, USER_ID) VALUES('myname@email.com', 2);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, USER_ID) VALUES('thebeard@email.com', 3);

