INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('master@email.com', 25);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('myname@email.com', 20);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('thebeard@email.com', 30);

INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('LadyJustice', TRUE, 1);
INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('Heisenberg', TRUE, 2);
INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('HardenJ', FALSE, 3);

