INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('master@email.com', 22);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('myname@email.com', 20);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('thebeard@email.com', 30);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('watchtower@email.com', 36);
INSERT INTO T_CONTACT (EMAIL_ADDRESS, AGE) VALUES('greak@email.com', 25);

INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('LadyJustice', TRUE, 1);
INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('Heisenberg', TRUE, 2);
INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('HardenJ', FALSE, 3);
INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('Jimi', TRUE, 4);
INSERT INTO T_USER (USERNAME, ACTIVE, CONTACT_ID) VALUES('Giannis', TRUE, 5);


