CREATE TABLE T_USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR2(50),
  ACTIVE NUMBER(1,0)
);

CREATE TABLE T_CONTACT(
  CONTACT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  EMAIL_ADDRESS VARCHAR2(100),
  USER_ID BIGINT,
  FOREIGN KEY(USER_ID) REFERENCES T_USER(USER_ID)
);
