CREATE TABLE T_CONTACT(
  CONTACT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  EMAIL_ADDRESS VARCHAR2(100),
  AGE INTEGER
);

CREATE TABLE T_USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR2(50),
  ACTIVE BOOLEAN,
  CONTACT_ID BIGINT,
  FOREIGN KEY(CONTACT_ID) REFERENCES T_CONTACT(CONTACT_ID)
);
