CREATE TABLE T_PLAYER_DETAIL(
  PLAYER_DETAIL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TEAM VARCHAR2(100),
  AGE INTEGER
);

CREATE TABLE T_PLAYER(
  PLAYER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR2(50),
  SURNAME VARCHAR2(50),
  ACTIVE BOOLEAN,
  PLAYER_DETAIL_ID BIGINT,
  FOREIGN KEY(PLAYER_DETAIL_ID) REFERENCES T_PLAYER_DETAIL(PLAYER_DETAIL_ID)
);
